### ISSUE TITLE
Error: Az CLI Login failed. Please check the credentials and make sure az is installed on the runner.

### ISSUE THREAD

**Issue by ryancomia** [Azure/login#203]
Anyone can pls help me
i have tried multiple times and different versions but i cant seem to make it work.
i am certain the secrets are correct. i have re-keyed and regenrate number of times

![image](https://user-images.githubusercontent.com/52190657/154484465-9033d122-ef1e-4d21-a601-4d161c30a270.png)

![image](https://user-images.githubusercontent.com/52190657/154484830-e924acc6-820c-49be-9717-548184d75b97.png)

**Comment by BALAGA-GAYATRI** [comment]
@ryancomia @naseraldaher Can you refresh your credentials(create new ones using [this](https://github.com/Azure/login#configure-a-service-principal-with-a-secret)) and check again. This seems like a temporary issue.
Also, login action now supports OIDC login mechanism. Visit [this] to get started with OIDC login.

**Comment by naseraldaher** [comment]
Seems like azure/login@v1.4.3 fixes this issue as well without the need to refresh credentials.

**Comment by BALAGA-GAYATRI** [comment]
Great to hear that @naseraldaher !  FYI, `azure/login@v1` points to the latest `azure/login@v1.4.3`. Both should be working fine.

**Comment by mikhail-teslya** [comment]
Hi @BALAGA-GAYATRI, this is not fixed for me in `@1.4.3` (and not working with `@v1` reference either). Error is exactly the same as in the first message.

1. Credentials are for sure working fine, executed az login --service-principal -u <xx> --tenant <xx> -p <xx> postfixed with az account set --subscription <xx> locally with no problems
2. Attaching debug logs of workflow execution here (the main point was to find out az cli version for local comparison)
[azure-cli-workflow-run.txt](https://github.com/Azure/login/files/8132787/azure-cli-workflow-run.txt)


Please advise or maybe consider reopening the issue :). Thanks

**Comment by ryancomia** [comment]
ts still not working aswell for me

**Comment by naseraldaher** [comment]
Hi @BALAGA-GAYATRI, didn't work with using v1, tried on different workflows as well. Had to specify using 1.4.3 for it to actually work.
Seems like the SPN had some bug as well. Even though it was created in the correct subscription and worked with az login, it didn't work for workflows. Created new SPN and using the 1.4.3 and everything worked for me.

**Comment by mikhail-teslya** [comment]
@naseraldaher Hi, I am referencing `@v1.4.3` directly, but it's not working in my workflows (also visible from logs I uploaded to the previous message)
![image](https://user-images.githubusercontent.com/85156799/155686565-ea7b26dc-25dc-475d-bf4a-129ecde4865c.png)

**Comment by naseraldaher** [comment]
@mikhail-teslya : Did you try creating new SPNs?

**Comment by mikhail-teslya** [comment]
@naseraldaher If you mean service principals in Azure then yes, quite a few, multiple times, and also always tested login using a referenced service principal locally (using az cli)

**Comment by pattisanta** [comment]
I have the same issue I have created a new SP changed the workflow. I can log in locally with the SP to the subscription successfully.  Just the workflow is not workings.
- name: Log in to subscription
        if: env.subscription == 'subscriptionName'
        uses: azure/login@v1.4.3    
        with:
          creds: ${{ secrets.name }}

**Comment by u7x3611** [comment]
I am also trying Windows Self hosted runner and it fails even i have CLI installed on machine, any idea?

**Comment by pavankmr850** [comment]
I came across same issue, however, this is resolved after providing { Open and closing braces } in the new secret as below. Please check if this helps you or not.

{
"clientId": 
  "clientSecret": 
  "subscriptionId":
  "tenantId": 
  "activeDirectoryEndpointUrl": "",
  "resourceManagerEndpointUrl": ",
  "activeDirectoryGraphResourceId":
  "sqlManagementEndpointUrl": 
  "galleryEndpointUrl": 
  "managementEndpointUrl": 
}

**Comment by edstv** [comment]
is it mandatory to include the endpoint urls?

**Comment by YanaXu** [comment]
Hi @pavankmr850 & @edstv, please open a new issue if you have more questions. A comment on a "closed" issue may be missed.

**Comment by mnlx** [comment]
I ran into the same problem today, it seems to be an issue with how the action loads the secrets. I minified my JSON credentials and it started working.
